/*
 * Copyright (C) 2018 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <unistd.h>
#include <string>

#include <android-base/file.h>
#include <android-base/test_utils.h>
#include <gtest/gtest.h>

#include "CppGen.h"

namespace {

constexpr const char* kTestSyspropFile =
    R"(owner: Platform
module: "android.os.PlatformProperties"
prefix: "android.os"

prop {
    name: "test_double"
    type: Double
    scope: Internal
}
prop {
    name: "test_int"
    type: Integer
    scope: Public
}
prop {
    name: "test.string"
    type: String
    scope: System
    readonly: true
}

prop {
    name: "test.enum"
    type: Enum
    enum_values: "a|b|c|D|e|f|G"
    scope: Internal
    readonly: false
}
prop {
    name: "test_BOOLeaN"
    type: Boolean
    scope: Public
}
prop {
    name: "longlonglongLONGLONGlongLONGlongLONG"
    type: Long
    scope: System
}

prop {
    name: "test_double_list"
    type: DoubleList
    scope: Internal
}
prop {
    name: "test_list_int"
    type: IntegerList
    scope: Public
}
prop {
    name: "test.strlist"
    type: StringList
    scope: System
    readonly: false
}

prop {
    name: "el"
    type: EnumList
    enum_values: "enu|mva|lue"
    scope: Internal
}
)";

constexpr const char* kExpectedHeaderOutput =
    R"(// Generated by the sysprop generator. DO NOT EDIT!

#ifndef SYSPROPGEN_android_os_PlatformProperties_H_
#define SYSPROPGEN_android_os_PlatformProperties_H_

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::os::PlatformProperties {

std::optional<double> test_double();

std::optional<std::int32_t> test_int();

std::optional<std::string> test_string();

enum class test_enum_values {
    a,
    b,
    c,
    D,
    e,
    f,
    G,
};

std::optional<test_enum_values> test_enum();
bool test_enum(const test_enum_values& value);

std::optional<bool> test_BOOLeaN();

std::optional<std::int64_t> longlonglongLONGLONGlongLONGlongLONG();

std::optional<std::vector<double>> test_double_list();

std::optional<std::vector<std::int32_t>> test_list_int();

std::optional<std::vector<std::string>> test_strlist();
bool test_strlist(const std::vector<std::string>& value);

enum class el_values {
    enu,
    mva,
    lue,
};

std::optional<std::vector<el_values>> el();

}  // namespace android::os::PlatformProperties

#endif  // SYSPROPGEN_android_os_PlatformProperties_H_
)";

constexpr const char* kExpectedSourceOutput =
    R"(// Generated by the sysprop generator. DO NOT EDIT!

#include "PlatformProperties.h"

#include <cstring>
#include <iterator>
#include <utility>

#include <dlfcn.h>
#include <strings.h>

#include <android-base/logging.h>
#include <android-base/parseint.h>
#include <android-base/stringprintf.h>
#include <android-base/strings.h>

namespace {

template <typename T> constexpr bool is_vector = false;

template <typename T> constexpr bool is_vector<std::vector<T>> = true;

template <typename T> std::optional<T> DoParse(const char* str);

template <> [[maybe_unused]] std::optional<bool> DoParse(const char* str) {
    static constexpr const char* kYes[] = {"1", "on", "true", "y", "yes"};
    static constexpr const char* kNo[] = {"0", "off", "false", "n", "no"};

    for (const char* yes : kYes) {
        if (strcasecmp(yes, str) == 0) return std::make_optional(true);
    }

    for (const char* no : kNo) {
        if (strcasecmp(no, str) == 0) return std::make_optional(false);
    }

    return std::nullopt;
}

template <> [[maybe_unused]] std::optional<std::int32_t> DoParse(const char* str) {
    std::int32_t ret;
    bool success = android::base::ParseInt(str, &ret);
    return success ? std::make_optional(ret) : std::nullopt;
}

template <> [[maybe_unused]] std::optional<std::int64_t> DoParse(const char* str) {
    std::int64_t ret;
    bool success = android::base::ParseInt(str, &ret);
    return success ? std::make_optional(ret) : std::nullopt;
}

template <> [[maybe_unused]] std::optional<double> DoParse(const char* str) {
    int old_errno = errno;
    errno = 0;
    char* end;
    double ret = std::strtod(str, &end);
    if (errno != 0) {
        return std::nullopt;
    }
    if (str == end || *end != '\0') {
        errno = old_errno;
        return std::nullopt;
    }
    errno = old_errno;
    return std::make_optional(ret);
}

template <> [[maybe_unused]] std::optional<std::string> DoParse(const char* str) {
    return std::make_optional(str);
}

template <typename Vec> [[maybe_unused]] std::optional<Vec> DoParseList(const char* str) {
    Vec ret;
    for (auto&& element : android::base::Split(str, ",")) {
        auto parsed = DoParse<typename Vec::value_type>(element.c_str());
        if (!parsed) {
            return std::nullopt;
        }
        ret.emplace_back(std::move(*parsed));
    }
    return std::make_optional(std::move(ret));
}

template <typename T> inline std::optional<T> TryParse(const char* str) {
    if constexpr(is_vector<T>) {
        return DoParseList<T>(str);
    } else {
        return DoParse<T>(str);
    }
}

[[maybe_unused]] std::string FormatValue(std::int32_t value) {
    return std::to_string(value);
}

[[maybe_unused]] std::string FormatValue(std::int64_t value) {
    return std::to_string(value);
}

[[maybe_unused]] std::string FormatValue(double value) {
    return android::base::StringPrintf("%.*g", std::numeric_limits<double>::max_digits10, value);
}

[[maybe_unused]] std::string FormatValue(bool value) {
    return value ? "true" : "false";
}

[[maybe_unused]] std::string FormatValue(std::string value) {
    return value;
}

template <typename T>
[[maybe_unused]] std::string FormatValue(const std::vector<T>& value) {
    if (value.empty()) return "";

    std::string ret;

    for (auto&& element : value) {
        if (ret.empty()) ret.push_back(',');
        ret += FormatValue(element);
    }

    return ret;
}

namespace libc {

struct prop_info;

const prop_info* (*system_property_find)(const char* name);

void (*system_property_read_callback)(
    const prop_info* pi,
    void (*callback)(void* cookie, const char* name, const char* value, std::uint32_t serial),
    void* cookie
);

int (*system_property_set)(const char* key, const char* value);

void* handle;

__attribute__((constructor)) void load_libc_functions() {
    handle = dlopen("libc.so", RTLD_LAZY | RTLD_NOLOAD);

    system_property_find = reinterpret_cast<decltype(system_property_find)>(dlsym(handle, "__system_property_find"));
    system_property_read_callback = reinterpret_cast<decltype(system_property_read_callback)>(dlsym(handle, "__system_property_read_callback"));
    system_property_set = reinterpret_cast<decltype(system_property_set)>(dlsym(handle, "__system_property_set"));
}

__attribute__((destructor)) void release_libc_functions() {
    dlclose(handle);
}

template <typename T>
std::optional<T> GetProp(const char* key) {
    auto pi = system_property_find(key);
    if (pi == nullptr) return std::nullopt;
    std::optional<T> ret;
    system_property_read_callback(pi, [](void* cookie, const char*, const char* value, std::uint32_t) {
        *static_cast<std::optional<T>*>(cookie) = TryParse<T>(value);
    }, &ret);
    return ret;
}

}  // namespace libc

using namespace android::os::PlatformProperties;

constexpr const std::pair<const char*, test_enum_values> test_enum_list[] = {
    {"a", test_enum_values::a},
    {"b", test_enum_values::b},
    {"c", test_enum_values::c},
    {"D", test_enum_values::D},
    {"e", test_enum_values::e},
    {"f", test_enum_values::f},
    {"G", test_enum_values::G},
};

template <>
std::optional<test_enum_values> DoParse(const char* str) {
    for (auto [name, val] : test_enum_list) {
        if (strcmp(str, name) == 0) {
            return val;
        }
    }
    return std::nullopt;
}

std::string FormatValue(test_enum_values value) {
    for (auto [name, val] : test_enum_list) {
        if (val == value) {
            return name;
        }
    }
    LOG(FATAL) << "Invalid value " << static_cast<std::int32_t>(value) << " for property " << android.ostest_enum;
}

constexpr const std::pair<const char*, el_values> el_list[] = {
    {"enu", el_values::enu},
    {"mva", el_values::mva},
    {"lue", el_values::lue},
};

template <>
std::optional<el_values> DoParse(const char* str) {
    for (auto [name, val] : el_list) {
        if (strcmp(str, name) == 0) {
            return val;
        }
    }
    return std::nullopt;
}

}  // namespace

namespace android::os::PlatformProperties {

std::optional<double> test_double() {
    return libc::GetProp<double>("ro.android.os.test_double");
}

std::optional<std::int32_t> test_int() {
    return libc::GetProp<std::int32_t>("ro.android.os.test_int");
}

std::optional<std::string> test_string() {
    return libc::GetProp<std::string>("ro.android.os.test.string");
}

std::optional<test_enum_values> test_enum() {
    return libc::GetProp<test_enum_values>("android.os.test.enum");
}

bool test_enum(const test_enum_values& value) {
    return libc::system_property_set("android.os.test.enum", FormatValue(value).c_str()) == 0;
}

std::optional<bool> test_BOOLeaN() {
    return libc::GetProp<bool>("ro.android.os.test_BOOLeaN");
}

std::optional<std::int64_t> longlonglongLONGLONGlongLONGlongLONG() {
    return libc::GetProp<std::int64_t>("ro.android.os.longlonglongLONGLONGlongLONGlongLONG");
}

std::optional<std::vector<double>> test_double_list() {
    return libc::GetProp<std::vector<double>>("ro.android.os.test_double_list");
}

std::optional<std::vector<std::int32_t>> test_list_int() {
    return libc::GetProp<std::vector<std::int32_t>>("ro.android.os.test_list_int");
}

std::optional<std::vector<std::string>> test_strlist() {
    return libc::GetProp<std::vector<std::string>>("android.os.test.strlist");
}

bool test_strlist(const std::vector<std::string>& value) {
    return libc::system_property_set("android.os.test.strlist", FormatValue(value).c_str()) == 0;
}

std::optional<std::vector<el_values>> el() {
    return libc::GetProp<std::vector<el_values>>("ro.android.os.el");
}

}  // namespace android::os::PlatformProperties
)";

}  // namespace

using namespace std::string_literals;

TEST(SyspropTest, CppGenTest) {
  TemporaryFile temp_file;

  // strlen is optimized for constants, so don't worry about it.
  ASSERT_EQ(write(temp_file.fd, kTestSyspropFile, strlen(kTestSyspropFile)),
            strlen(kTestSyspropFile));
  close(temp_file.fd);
  temp_file.fd = -1;

  TemporaryDir temp_dir;

  std::string err;
  ASSERT_TRUE(
      GenerateCppFiles(temp_file.path, temp_dir.path, temp_dir.path, &err));
  ASSERT_TRUE(err.empty());

  std::string header_output_path = temp_dir.path + "/PlatformProperties.h"s;
  std::string source_output_path = temp_dir.path + "/PlatformProperties.cpp"s;

  std::string header_output;
  ASSERT_TRUE(android::base::ReadFileToString(header_output_path,
                                              &header_output, true));
  ASSERT_EQ(header_output, kExpectedHeaderOutput);

  std::string source_output;
  ASSERT_TRUE(android::base::ReadFileToString(source_output_path,
                                              &source_output, true));
  ASSERT_EQ(source_output, kExpectedSourceOutput);

  unlink(header_output_path.c_str());
  unlink(source_output_path.c_str());
}
